version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependencies
    ignore:
      - dependency-name: "node"
        versions: ["21.x"]
    commit-message:
      prefix: "build(dependencies):"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    target-branch: main
    labels:
      - dependencies
    commit-message:
      prefix: "build(dependencies):"
